### PR TITLE
reshuffle 2 includes to better fit hirarchy

### PR DESCRIPTION
**Pull request by redjard**
moved `#include "GUI/gui.h"` up before `#include "Hitbox.h"` and `#include "Hitbox.h"` down, both after renderers but before other game active classes. Hitbox.h needs some specific gui class, but that doesn't import gui.h, causing issues. gui needs the renderers, so that's why the two are where they are.

### CODE REVIEW

**Comment by Mashpoe** [comment]
As far as I know, there isn't any reason Hitbox.h should require something directly from GUI.h. Are you sure there isn't something that GUI.h includes that Hitbox.h requires? I also think that whatever Hitbox.h requires should be directly included in Hitbox.h, because relying on the order of includes is generally considered a bad practice.

**Comment by redjard** [comment]
```
4dm.h/GUI/Element.h: At global scope:
4dm.h/GUI/Element.h:8:14: error: use of enum ‘AlignmentX’ without previous declaration
    8 |         enum AlignmentX;
      |              ^~~~~~~~~~
4dm.h/GUI/Element.h:9:14: error: use of enum ‘AlignmentY’ without previous declaration
    9 |         enum AlignmentY;
      |              ^~~~~~~~~~
```
Element.h uses the alignmentX and Y enums, and cpp proper doesn't allow using enums blindly. There is probably a way to tell the compiler we define them later, but it seems unnecessary when we could just import gui in its entirety before the other stuff

_disclaimer: my cpp experience is currently sitting at a proud about 1 week_

**Comment by Mashpoe** [comment]
That's Element.h, not Hitbox.h. Hitbox.h doesn't need element alignment, it is for the Hitbox class that is used by entities. Also, good luck on learning C++. I have been using it for about 7 years and I still have issues.

**Comment by redjard** [comment]
Ah, I missed the top of the error:
```
In file included from 4dm.h/CraftingMenu.h:6,
                 from 4dm.h/InventoryManager.h:4,
                 from 4dm.h/Player.h:5,
                 from 4dm.h/World.h:6,
                 from 4dm.h/Entity.h:6,
                 from 4dm.h/Hitbox.h:4,
                 from 4dm.h/4dm.h:103:
4dm.h/GUI/Element.h: At global scope:
4dm.h/GUI/Element.h:8:14: error: use of enum ‘AlignmentX’ without previous declaration
    8 |         enum AlignmentX;
      |              ^~~~~~~~~~
4dm.h/GUI/Element.h:9:14: error: use of enum ‘AlignmentY’ without previous declaration
    9 |         enum AlignmentY;
      |              ^~~~~~~~~~
```
I think this shows the history of how in the world that dependency "migrated that far downwards in the dependency chain"

**Comment by Mashpoe** [comment]
That's interesting. I don't really know what's going on with the includes in this project. Maybe Tr1Ngle will have a better solution. It looks like an [earlier commit](https://github.com/4D-Modding/4dm.h/commit/a59ea16fd503c7bd1985b709de22191589a463dc#diff-d5c4811e13736820441e106656df9ee66065de442c2c9170a58acf54887ac7e8) removed the gui.h include from Element.h so that Element.h could be included in gui.h instead, but that meant that the enums had to be forward declared in Element.h, and for some reason that's causing issues.

**Comment by Tr1NgleDev** [comment]
it doesn't cause any issues with visual studio C++ compiler tho. It's only a problem when using mingw

**Comment by Mashpoe** [comment]
gcc probably doesn't like enum forward declarations.

**Comment by redjard** [comment]
msvc allows a bunch of stuff that it probably shouldn't, it seems to pass some of tr1ngles generated code without complaint that I get massive errors for using -std=c++20 and that is outright not accepted anymore in -std=c++23

**Comment by Tr1NgleDev** [comment]
ig so

**Comment by Mashpoe** [comment]
I think it will compile with MinGW if you include an underlying type in the forward declaration, e.g. `enum AlignmentX : int`. You might have to do the same thing for the actual definition in gui.h.

**Comment by redjard** [comment]
That works, yeah. I think it's only right to do that if the 4dm source also sets enums to int. It's not been that long since enums commonly where smaller than int, and I wouldn't be surprised if they become u64 in the future, maybe even depending on their size.

**Comment by redjard** [comment]
uh, guess gh can close pull requests without warning sometimes when renaming branches. Great
Just pretend this was still open
